repos:
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    -   id: black
- repo: https://github.com/asottile/blacken-docs
  rev: v1.12.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==21.5b0]
    exclude: README.md