_fw_name: CommonAdapter
_fw_q_type: SLURM
rocket_launch: rlaunch -w /path/to/fw_config/my_fworker.yaml singleshot
nodes: 2
walltime: '00:30:00'
account: ???
job_name: knl_launcher
qos: debug
constraint: 'knl'
pre_rocket: |
            module load vasp/6.2.1-knl
            export VASP_PARALLEL_CMD='srun -N 2 --ntasks-per-node 64 -c 4 --cpu_bind=cores'
            export OMP_PROC_BIND=true
            export OMP_PLACES=threads
            export OMP_NUM_THREADS=1
