name: deploy

on:
  workflow_run:
    workflows: [testing]
    types:
      - completed
jobs:
  deploy-docs:
    if: ${{ github.repository_owner == 'arosen93' && github.event.workflow_run.conclusion == 'success'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Install pandoc
        run: sudo apt-get install pandoc
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .[docs]
      - name: Build
        run: sphinx-build docs/src docs_build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs_build