name: tests
on:
  push:

  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: [ '3.8', '3.9' ]
    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      - name: Get Date
        id: get-date
        run: echo "::set-output name=today::$(/bin/date -u '+%Y%m%d')"
        shell: bash

      - name: Cache Conda env
        uses: actions/cache@v2
        with:
          path: ${{ env.CONDA }}/envs
          key: conda-${{ runner.os }}--${{ runner.arch }}--${{ steps.get-date.outputs.today }}-${{ hashFiles('etc/example-environment-caching.yml') }}-${{ env.CACHE_NUMBER }}
        env:
          CACHE_NUMBER: 0
        id: cache

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          conda install -c psi4 psi4
          conda install -c conda-forge xtb-python dftbplus
          pip install .[tests]
          pip install pytest-cov

      - name: Run tests with pytest
        run: pytest --cov=quacc --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        if: github.repository == 'arosen93/quacc'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pandoc
        run: sudo apt-get install pandoc
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .[docs]
      - name: Build
        run: sphinx-build docs/src docs_build
