name: Tests
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip cache purge
          pip install -r requirements.txt
          conda install -c conda-forge xtb-python
          pip install .[tests]
          pip install pytest-cov

      - name: Run tests with pytest
        run: pytest --cov=quacc --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        if: github.repository == 'arosen93/quacc'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
